### ISSUE TITLE
error when launching from usb

### ISSUE THREAD

**Issue by Armandokevin** [supergrub/supergrub#103]
Hello

I don't get supergrub2 disk, I always get grub rescue, on a black screen

Thanks in advance

**Comment by adrian15** [comment]
You are probably using a random tool for putting ISOs into USBs.
I recommend you to use Balena Etcher or make sure to use the dd mode in some of those tools so that the complete usb drive is erased. (Be careful about it.)

If you manage to boot from it in a system but not in another system then, yes, it's a bug.

I will close this issue for now.
