### ISSUE TITLE
"error: unknown filesystem" on usb (UEFI boot option)

### ISSUE THREAD

**Issue by terauck21** [supergrub/supergrub#35]
We spoke yesterday about a failure to get a grub menu for super_grub2_disk_hybrid_2.02s10.iso.  I have tried again with super_grub2_disk_hybrid_2.04rc1s1-beta4.iso as you suggested.  I got the same result, i.e. "error : unknown filesystem" following by the "grub rescue>" prompt.
This computer model is PRIME H310M-A R2.0 v.
This time I tried some commands.  'ls' resulted in about 18 entries.  After trying about 8 others, I got a positive response to 'ls (hd0,1)/'.  Grub rescue accepted the command to set that as root.  I got as far as 'ls (hd0,1)/boot/grub/i386-efi/'; the output scrolled off the page and I couldn't remember how to stop that happening.  In any case, there was nothing more I could think of; 'insmod normal' resulted in the same error message; the help I found on line related to operating systems and, of course, in this case there is no 'vmlinuz' file or initrd.img.  Grub rescue didn't recognise the command 'boot'.
I doubt that any other versions or Rescatux will produce a different result but I am happy to try such as you suggest.

**Comment by terauck21** [comment]
I have written Rescatux to a USB.  An error message flashed briefly, then I was able to boot and save settings.  It seems to be a Debian live os; I'd sooner use my own live os.

**Comment by terauck21** [comment]
How did I 'close' this issue?  I did not intend to.

**Comment by terauck21** [comment]
Re-opened, I think.

**Comment by adrian15** [comment]
1) Your original issue is that when booting either:
* super_grub2_disk_hybrid_2.02s10.iso
or
super_grub2_disk_hybrid_2.04rc1s1-beta4.iso
you are never able to see the Super Grub2 Disk main menu ( https://www.supergrubdisk.org/wp-content/uploads/2014/03/super_grub2_disk_2.01-rc2_main_menu.png ).

Instead you get the
`grub rescue>`
prompt.

Can you please confirm me that I am describing it right?

2) rescatux-0.71-beta7.iso boots for you. That makes sense because its disk boot-wise it's built with a different method than the one from Super Grub2 Disk.

3) Super Grub2 Disk 2.04s1 is out. You might try it. Although I doubt there is going to be any difference from super_grub2_disk_hybrid_2.04rc1s1-beta4.iso .

Thank you for your feedback.

**Comment by terauck21** [comment]
Yes, that is the issue.  The new iso will not be any different unless the issue has been addressed.  Rescatux is similar to a live usb/disk.  Is there perhaps a command on the super grub usb which can be executed to provide the menu?

**Comment by adrian15** [comment]
Can you please try latest stable version (2.04s1)?
With another usb device too just in case it's a bad sector problem?

@terauck21 : If it still fails would you please connect to [#sgrub channel on freenode](https://www.supergrubdisk.org/chat/) and ask for me so that I can inspect the error live?

Thank you.

**Comment by adrian15** [comment]
@terauck21 : Does the new https://sourceforge.net/projects/supergrub2/files/2.04s2-beta2/super_grub2_disk_2.04s2-beta2/supergrub2-2.04s2-beta2-multiarch-USB.img.zip/download (which you would need to unzip) works for your specific firmware?

Thank you.

**Comment by shirishag75** [comment]
@adrian15 I got the same issue. I tried the latest stable 
super_grub2_disk_x86_64_efi_2.04s1 and got the same exact issue as outlined in - 

https://lists.debian.org/debian-user/2019/11/msg00201.html

**Comment by shirishag75** [comment]
FWIW, with the newer image i.e. 2.04s2 was able to get the menu and was also able to getinto my beloved debian . Did update-grub which added a boot entry which probably was messed by some MS-Windows update :(

**Comment by adrian15** [comment]
@shirishag75 : Your information is a bit confusing.
1) Do you confirm that initially used Super Grub2 Disk 2.04s1 dd'ed to a usb but you couldn't use its menu but instead you got `grub rescue>` ?

2) And do you confirm that you later used 2.04s2-beta2 dd'ed to a usb and instead of getting `grub rescue>` you got the proper Super Grub2 Disk menu?

3) Can you please describe
 - how you booted in each time (BIOS / UEFI)?
 - your computer/laptop model
 - UEFI firmware version

?

Thank you.

**Comment by shirishag75** [comment]
Replying in-line . Wlll update it as I am able to provide more and more info. 

> @shirishag75 : Your information is a bit confusing.
> 
>     1. Do you confirm that initially used Super Grub2 Disk 2.04s1 dd'ed to a usb but you couldn't use its menu but instead you got `grub rescue>` ?
> 

Initially I didn't use DD but used iso via rufus on MS-Windows as grub2 menu on Debian disappeared. On the machine I am/was troubleshooting I was in MS-Windows 10 and used rufus 3.8 to and used ISO instead of DD to put the image on the usb disk. 

https://github.com/pbatard/rufus/releases/download/v3.8/rufus-3.8.exe

Subsequently, when I booted via UEFI the usb dropped me to grub rescue. 

>     2. And do you confirm that you later used 2.04s2-beta2 dd'ed to a usb and instead of getting `grub rescue>` you got the proper Super Grub2 Disk menu?
> 

Subsequently on reading the conversation I again used rufus, this time though used rufus and DD'ed the .img file via rufus. 

>     3. Can you please describe
> 
> 
>     * how you booted in each time (BIOS / UEFI)?
> 

UEFI

>     * your computer/laptop model

It's an assembled machine but do have the details as under - 

$ inxi -M
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME Z270-P v: Rev X.0x serial: <root required>  UEFI: American Megatrends v: 0808 date: 06/16/2017

>     * UEFI firmware version

Info. given above. 
 
> Thank you.

Please let me know if you need any more info.

**Comment by adrian15** [comment]
> On the machine I am/was troubleshooting I was in MS-Windows 10 and used rufus 3.8 to and used ISO instead of DD to put the image on the usb disk.
> 
> Subsequently on reading the conversation I again used rufus, this time though used rufus and DD'ed the .img file via rufus.

Yeah, that makes sense. I didn't remember too much this issue and I thought the problem was solved by just using a newer SG2D version (e.g. in ISO image) but that's not the case.

The problem is probably solved by using the IMG image because it has a proper hard disk layout (and not an hybrid one). Some UEFI firmware might not handle properly the hybrid nature (cdrom+hard disk layout in one image) of SG2D ISOs.

So far you have tested:
 - SG2D 2.04s1 hybrid iso
 - SG2D 2.04s2-beta2 multiarch img

.

Can you please test:
 - supergrub2-2.04s2-beta2-multiarch-CD.iso
and report back if, as I now suspect, you get `grub rescue>` prompt instead of Super Grub2 Disk menu ?

Thank you.

**Comment by shirishag75** [comment]
I would do that gladly as well, although in the interim I also updated my UEFI which fixed the debian label not coming in - 

```
$ inxi -M
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME Z270-P v: Rev X.0x serial: <root required> UEFI: American Megatrends v: 1205 date: 05/11/2018
```

**Comment by shirishag75** [comment]
at bottom :-

<snipped>
 
> Can you please test:
> 
>     * supergrub2-2.04s2-beta2-multiarch-CD.iso
>       and report back if, as I now suspect, you get `grub rescue>` prompt instead of Super Grub2 Disk menu ?
> 

You mean this one ?

https://sourceforge.net/projects/supergrub2/files/2.04s2-beta2/super_grub2_disk_2.04s2-beta2/supergrub2-2.04s2-beta2-x86_64_efi-CD.iso/download
> Thank you.

**Comment by adrian15** [comment]
> ```
> $ inxi -M
> Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME Z270-P v: Rev X.0x serial: <root required> UEFI: American Megatrends v: 1205 date: 05/11/2018
> ```

I need to add inxi to Rescapp, probably as a Boot Info Script complement or replacement.

**Comment by adrian15** [comment]
> > Can you please test:
> > ```
> > * supergrub2-2.04s2-beta2-multiarch-CD.iso
> >   and report back if, as I now suspect, you get `grub rescue>` prompt instead of Super Grub2 Disk menu ?
> > ```
> 
> You mean this one ?
> 
> https://sourceforge.net/projects/supergrub2/files/2.04s2-beta2/super_grub2_disk_2.04s2-beta2/supergrub2-2.04s2-beta2-x86_64_efi-CD.iso/download

No, I mean [supergrub2-2.04s2-beta2-multiarch-CD.iso](https://sourceforge.net/projects/supergrub2/files/2.04s2-beta2/super_grub2_disk_2.04s2-beta2/supergrub2-2.04s2-beta2-multiarch-CD.iso/download) which it's the equivalent to the hybrid iso on older SG2D versions.

**Comment by adrian15** [comment]
> Thank you for making our lives easier.

If you want to thank me back, after your current test, you can put back the _SG2D 2.04s2-beta2 multiarch img_ on the usb, expand the BOOTISOS partition, put [rescatux-0.72-beta2.iso](https://sourceforge.net/projects/rescatux/files/rescatux-0.72-beta2/rescatux-0.72-beta2.iso/download) there and try Rescatux 0.72-beta2 and give us feedback on [Rescapp github issues page](https://github.com/rescatux/rescapp/issues) so that I can finally release its stable version.

**Comment by shirishag75** [comment]
I will have to take a rain check on it for couple of days. The thing is, now a days most of the flash drives which are available in the market are either TLC or QLC flash memories. https://en.wikipedia.org/wiki/Multi-level_cell . Most of the flash drives I have purchased recently haven't lasted long, at the most 6 months :( . I still will be buying a couple but will take couple of days. Only after that, I would be able test out the various scenarios you want. This will also probably help improve my knowledge of the products mentioned therein :)

**Comment by shirishag75** [comment]
I blogged a bit about my whole experience and it genesis at https://flossexperiences.wordpress.com/2019/11/07/a-tale-of-unfortunate-coincidences-and-incidents/
