### ISSUE TITLE
How to change default options?

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#36]
I couldn't find it in the README and the wiki seems to be an empty white page with just a tracker.

Do I have to rebuild the entire project to flip the one bit for whether to scan the supergrub disk itself?

Anyway, many thanks for this great project!

**Comment by mk-pmb** [comment]
As a work-around I made [this patcher](https://github.com/mk-pmb/supergrubdisk-patcher-bash).

**Comment by adrian15** [comment]
The sort of official method for customizing SG2D is that if you have it in a writable filesystem you can create an sgd_custom.cfg file to add your own code at the main menu bottom.

https://github.com/supergrub/supergrub/blob/2.04s1/menus/sgd/main.cfg#L282-L293

And, yes, it would be nice if you could built it so that the build documentation can be improved.

Pull requests are welcome.

**Comment by adrian15** [comment]
> Do I have to rebuild the entire project to flip the one bit for whether to scan the supergrub disk itself?
> As a stopgap/work-around I made this patcher.
Now that I see your patcher I understand what you mean.

```
sgdsearch='on'
export sgdsearch
```

Either:
* You add the sgd_custom.cfg file to run that those lines
* You build SG2D from scratch (Feedback on documentation is welcome)
* You try to repack the iso.

In order to the repack the iso (which might be the easiest option) this page might help you:
https://wiki.debian.org/RepackBootableISO
to find an easier way to repack SG2D.

**Comment by mk-pmb** [comment]
Thanks for those pointers! It will probably be a few months until I find time for this again, though.

**Comment by adrian15** [comment]
@mk-pmb : You should be able to edit files on future usb versions of Super Grub2 Disk. We need your valuable feedback at : #40 to push it forward.

Thank you.

Closing the bug.
