### ISSUE TITLE
Include a 32bit uefi

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#37]
Hi! I like supergrub because usually it can boot everywhere… except on an Acer Aspire SW5-012. I managed to create some generic GRUB for it using [this tutorial](https://gist.github.com/mk-pmb/512a8105d3b39e55152c7fda248cd976) and it manages to boot my live Ubuntu but it doesn't seem to work with casper. Please make the SuperGRUB even more super so it runs on exotic Acer netbooks, too.

**Comment by adrian15** [comment]
The always recommended [super_grub2_disk_hybrid_2.04s1.iso](https://sourceforge.net/projects/supergrub2/files/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso/download) should boot in your system.
If you want an specific (It will only boot in your machine) 32bit uefi iso you can try [super_grub2_disk_i386_efi_2.04s1.iso](https://sourceforge.net/projects/supergrub2/files/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_i386_efi_2.04s1.iso/download) .

Feedback is welcomed because if the specific iso boots but not the hybrid one then that means that either your firmware has a bug or that SG2D hybrid version has a bug.

**Comment by mk-pmb** [comment]
> The always recommended

Was it really recommended before Aug 26, 2019? ;-) Anyway, thanks for pointing out that new version. I tested it and it works. :+1:

**Comment by mk-pmb** [comment]
I was just reminded why I did not use the `2.04rc1s1-beta4`, and cannot use 2.04 as intended. I'll report that problem separately.
