### ISSUE TITLE
How to boot an ISO within /boot/boot-isos

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#54]
I am using  supergrub2-2.04s2-beta2-multiarch-CD.iso which is written to both a DVD as well as using it written to a USB stick.
* I have written several ISOs to /boot/boot-isos (including Ubuntu, Rescatux, SG2D isos)
* I have experienced success in booting several ISOs that have loopback.cfg files via **"Select and Show Boot Methods"** option.
* I have read several web discussions on GRUB2 and loopback.cfg. 

BUT I remain in the dark on 
* how loopback file is used, 
* where in the booting process it is accessed, 
* which order of hierarchy is in place and 
* a guide to any utility(s) that would be useful in producing a loopback.cfg file for an ISO that has GRUB2's grub.cfg, **but no loopback.cfg is present** that can be used by SuperGRUB2 selection as a candidate for booting

I am appealing, here on GIT, for guidance using a Puppy Linux distro's ISO as a test for creating a loopback.cfg file on a PUP which is booting a GRUB2 boot-manager (grub.cfg). I am clueless to begin assembly of one for SG2D selection for boot.

Thanks in advance to anyone who is willing to guide

**BTW:** The picture on SG2D beta2 webpage (https://www.supergrubdisk.org/category/download/supergrub2diskdownload/super-grub2-disk-beta/) does not match the current ISO/IMG. You may want to replace it.

**Comment by adrian15** [comment]
> I am using supergrub2-2.04s2-beta2-multiarch-CD.iso which is written to both a DVD as well as using it written to a USB stick.

If you are going to write an SG2D image into an USB stick please do not use the multiarch-CD iso but the multiarch-USB.img.zip image instead. This latter image will allow you to have an additional fat32 partition where to store iso files.

**Comment by adrian15** [comment]
> BTW: The picture on SG2D beta2 webpage (https://www.supergrubdisk.org/category/download/supergrub2diskdownload/super-grub2-disk-beta/) does not match the current ISO/IMG. You may want to replace it.

I am trying to focus on releasing an stable Rescatux release. Later on I might release an stable SG2D version with that image updated to the most current one.

The current image description _Super Grub2 Disk 2.01 rc2 Main Menu_ is accurate so I'm fine with that.

**Comment by CollaboratorGCM** [comment]
Thanks for your reply. 

I do understand your primary goal! And I understand that SG2D is secondary at this time.

If answering these are better suited for a later date, I could wait for after your release of upcoming Rescatux. 

I am attaching 2 files from SG2D's ISO/IMG, below, from SG2D's /boot/ directory. 
*Are they used together or separately?
*Which has hierarchy?
**GRUB.cfg**
```
insmod datehook

set sg2d_directory="${config_directory}/sgd"
export sg2d_directory
set afd_directory="${config_directory}"
export afd_directory

if [ "$MONTH" -eq "4" -a "$DAY" -eq "1" ] ; then
  configfile "${afd_directory}/afd2012.cfg"
else
  configfile "${sg2d_directory}/main.cfg"
fi
```
**LOOPBACK.cfg**
```
clear
echo "You are loopback booting Super Grub2 Disk"
echo "THIS IS NOT SUPPORTED"
echo "You are on your own."
echo ""
echo ""
echo ""
echo $"Press escape to continue to loopback booted Super Grub2 Disk"
sleep --interruptible 9999
source "(${root})/boot/grub/grub.cfg"
```

**Lastly** is there a loopback utility/sample to create its configuration file for a distro that doesn't have one?

**Comment by CollaboratorGCM** [comment]
Rescatux has the following in its /boot folder. Still trying to piece together how these work for SG2D's use. I have no problem booting Rescatux, but, I am not understanding how these files are needed and used.

An explanation of the relationship of the 2 following files may be a better suit? 
**LOOPBACK.cfg**
`source /boot/grub/grub.cfg`

**GRUB.cfg**
```
set default=0

loadfont $prefix/dejavu-bold-16.pf2
loadfont $prefix/dejavu-bold-14.pf2
loadfont $prefix/unicode.pf2
set gfxmode=auto
insmod all_video
insmod gfxterm
insmod png

set color_normal=light-gray/black
set color_highlight=white/black

if [ -e /isolinux/splash.png ]; then
    # binary_syslinux modifies the theme file to point to the correct
    # background picture
    set theme=/boot/grub/live-theme/theme.txt
elif [ -e /boot/grub/splash.png ]; then
    set theme=/boot/grub/live-theme/theme.txt
else
    set menu_color_normal=cyan/blue
    set menu_color_highlight=white/blue
fi

terminal_output gfxterm

insmod play
play 960 440 1 0 4 440 1

# Live boot
menuentry "Live system, kernel 4.19.0-6-amd64" {
	linux	/live/vmlinuz-4.19.0-6-amd64 boot=live config quiet splash locales=en_US.UTF-8 selinux=1 security=selinux enforcing=0 liveid=/LIVEID/49E394A2/FFEF872C/9781D013/606BD852 selinux=1 security=selinux enforcing=0 findiso=${iso_path}
	initrd	/live/initrd.img-4.19.0-6-amd64
}
menuentry "Live system, kernel 4.19.0-6-amd64 (fail-safe mode)" {
	linux	/live/vmlinuz-4.19.0-6-amd64 boot=live components memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=normal liveid=/LIVEID/49E394A2/FFEF872C/9781D013/606BD852
	initrd	/live/initrd.img-4.19.0-6-amd64
}
menuentry "Live system, kernel 4.19.0-6-686" {
	linux	/live/vmlinuz-4.19.0-6-686 boot=live config quiet splash locales=en_US.UTF-8 selinux=1 security=selinux enforcing=0 liveid=/LIVEID/49E394A2/FFEF872C/9781D013/606BD852 selinux=1 security=selinux enforcing=0 findiso=${iso_path}
	initrd	/live/initrd.img-4.19.0-6-686
}
menuentry "Live system, kernel 4.19.0-6-686 (fail-safe mode)" {
	linux	/live/vmlinuz-4.19.0-6-686 boot=live components memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=normal liveid=/LIVEID/49E394A2/FFEF872C/9781D013/606BD852
	initrd	/live/initrd.img-4.19.0-6-686
}
```

**Comment by adrian15** [comment]
Please create a new branch out of current master branch and add there the README.loopback.cfg.md file. These new file should replace the current https://www.supergrubdisk.org/wiki/Loopback.cfg with the following sections:
* Introduction
* Final user instructions
* Distro builder instructions
* Multi distro tools builder instructions

That way you will be able to create a new pull request and improve the current documentation. And maybe I might link to it from the liveid repo.

I will try later to draft here the Distro builder instructions part in this same issue.

**Comment by adrian15** [comment]
> What should be in a loopback configuration for SG2D?

This is a rushed explanation.

The only thing that SG2D does before configfile-ing into a loopback.cfg is setting up the ${iso_path} grub variable to:
```
/boot/boot-isos/mydistro.iso
```
or whatever it's the absolute path for the iso.

The rest of magic is left to the loopback.cfg, kernel and initrd contents which in most of the cases use the initrd option named `findiso=`.

**Comment by CollaboratorGCM** [comment]
Would you say the following is accurate?

   - "SG2D option "" searches the attached drives seeking installed OSes as
   well as ISOs in  /boot or /boot-iso or ..."
   - "If ISOs are found in the designated search folders, it scans each ISO
   looking for those which have a grub.cfg & a loopback.cfg file in the ISOs
   filesystem"
   - "If ISOs are found which contain such, they will be listed as
   candidates to be booted"

*True or False?*

Further,

   - "if any of the listed ISOs is selected, the ISO's grub.cfg is run,
   first...followed by the instructions in the loopback.cfg"

*Is this correct?*

**Comment by adrian15** [comment]
> Would you say the following is accurate? - "SG2D option "" searches the attached drives seeking installed OSes as well as ISOs in /boot or /boot-iso or ..." - "If ISOs are found in the designated search folders, it scans each ISO looking for those which have a grub.cfg & a loopback.cfg file in the ISOs filesystem" - "If ISOs are found which contain such, they will be listed as candidates to be booted" *True or False?*

It's true although there are more type of ISOs supported BUT we don't want to support them. We only want to support loopback.cfg because it's the way to go. It's the distro developer which should know what you are supposed to boot exactly, so it's the one to write loopback.cfg.

You can check associated source code for the algorithm you are describing on https://github.com/supergrub/supergrub/blob/master/menus/sgd/autoiso.cfg .

>  Further, - "if any of the listed ISOs is selected, the ISO's grub.cfg is run, first...followed by the instructions in the loopback.cfg" *Is this correct?*

No, that's not true. It configfiles into loopback.cfg, not to grub.cfg. Writing loopback.cfg in such a way that it just forwards boot handling to grub.cfg in the same disk is optional. It's usually done like this by distro developers so that they only have to care about updating grub.cfg. That means loopback.cfg file won't need to be updated each time a new kernel version is used on the iso.

I already said:

> The only thing that SG2D does before configfile-ing into a loopback.cfg is setting up the ${iso_path} grub variable to:
> ```
> /boot/boot-isos/mydistro.iso
> ```

which you can check here: https://github.com/supergrub/supergrub/blob/master/menus/sgd/autoiso.cfg#L36-L50 . It's a bit abstract I must admit.

**Comment by adrian15** [comment]
> * Introduction
> * Final user instructions
> * Distro builder instructions
> * Multi distro tools builder instructions

Please use this branch: https://github.com/supergrub/supergrub/tree/loopbackcfg-doc as a base for your work.

**Comment by adrian15** [comment]
## How an installed distro boots

Either thanks to UEFI or to BIOS an small (or bigger) program called boot loader is loaded into RAM.
Back in the day this program might be lilo or grub legacy. Nowadays it's grub2.

So this program grub2 which is loaded into RAM only knows how to talk to the CPU and how to write and read into the RAM. Thanks to its filesystem modules it manages to read the hard disk contents, its partitions and its partition filesystems. That means it can read files from the computer.

One of the partitions next to the `/boot/grub/grub.cfg` path is hardcorded into grub2 boot code specific for your machine.

Grub.cfg is set to do three things:
 - Mount the partition where kernel and initrd are to be found
 - Load kernel into RAM
 - Load kernel boot parametres into RAM
 - Uncompress and load initrd into RAM just after the kernel
 - Instruct the CPU to load the kernel program

Now the kernel does its job.
So this program Linux (as in Linux kernel) which is loaded into RAM only knows how to talk to the CPU and how to write and read into the RAM. Now either the kernel either has integrated filesystem modules or they will later be embedded into the initrd.

The kernel reads his boot parametres which one of them says:
```
root=UUID=6322
```
and saves it for later.

Although it's optional in most of the cases manages to start the only program he will only be handle. The PID 1. That is usually /bin/init inside the ram disk based image (initrd) which grub2 loaded previously into the RAM.

Now the initrd maybe loads some filesystem modules so that it can read all the ext4 partitions.

Initrd reads the kernel boot parametres with the before mentioned:
```
root=UUID=6322
```
.

So it's time to loop into all the known hard disks and filesystems inside of them till that specific UUID is found on one of them. That specific filesystem is mounted and what so far was the root filesytem (the init ram disk) now it's pivot_rooted into that specific UUID partition filesystem.

Now the UUID partition filesystem /bin/init is run.

That's it. For me the boot process stops here.

Whatever partitions are mounted or services are started thanks to the /bin/init (and the other files it reads) in your UUID partition filesystem is userspace boot (not sure about the proper name).

**Comment by CollaboratorGCM** [comment]
Thanks for explaining the Linux boot process. 

My primary need is purely to understand SG2D requirement for booting an ISO from /boot/boot-isos; specifically the process with the loopback.cfg requirement and how to setup for SG2D selection of the ISOs in that folder.

Thus far, I think you have alluded to the hierarchy for grub.cfg & loopback.cfg relationship. Now its a matter of taking a Puppy Linux distro which uses GRUB2, opening it using ISOmaster replacing its grub.cfg and adding a loopback.cfg that will guide booting the ISO...either in its standalone mode or via SG2D selection for ISO booting.

**Comment by adrian15** [comment]
> My primary need is purely to understand SG2D requirement for booting an ISO from /boot/boot-isos; specifically the process with the loopback.cfg requirement and how to setup for SG2D selection of the ISOs in that folder.

My primary need is having someone else (i.e. @CollaboratorGCM ) documenting this process so that future distro developers know how to use this specific feature. So far you have not said if you were willing to document it or not.

I'm not going to unveil you the last bits of what you need (not yet but I will) so that you leave and the documentation is once again unfinished and unpolished.

Please notice I'm not English native and, someone like you, whom might be English native might be more suited than me in order to collect all the knowledge related to this feature and write its nice documentation. Even if you are not English native you will be useful because you can understand the whole process from the point of view that does not know anything about SG2D, bootloaders and such.

**Comment by CollaboratorGCM** [comment]
I think I know the development people (and I am willing, too) that can/could/would be in a better position to complete the needed documentation to match the PUPPY distros mentioned.

I have sent an appeal to them. I am hopeful they will show up soon.

P.S. I did not mention it, but I did look over [your auto.cfg as you instructed here](https://github.com/supergrub/supergrub/issues/54#issuecomment-555927025).

**Comment by adrian15** [comment]
> I think I know the development people (and I am willing, too) that can/could/would be in a better position to complete the needed documentation to match the PUPPY distros mentioned.
> 
> I have sent an appeal to them. I am hopeful they will show up soon.
> 
> P.S. I did not mention it, but I did look over [your autoiso.cfg as you instructed here](https://github.com/supergrub/supergrub/issues/54#issuecomment-555927025).

Ok, I'll resume my feedback when I get some proof of README.loopback.cfg.md work in a derived branch of https://github.com/supergrub/supergrub/tree/loopbackcfg-doc in a github (or another public git website) forked repo then.

Good luck!

**Comment by CollaboratorGCM** [comment]
[Thought this would interest you: **loopback.cfg**](https://github.com/puppylinux-woof-CE/woof-CE/issues/1672#issuecomment-557850250)

**Comment by CollaboratorGCM** [comment]
[Thought this would interest you: **loopback.cfg**](https://github.com/puppylinux-woof-CE/woof-CE/issues/1672#issuecomment-557850250) 

Puppy Linux developers are attempting to address. 

If there is a suggestion to them, I am sure they will respond.

**Comment by adrian15** [comment]
I'll resume my feedback when I get some proof of [README.loopback.cfg.md](https://github.com/supergrub/supergrub/blob/loopbackcfg-doc/README.loopback.cfg.md) work in a derived branch of https://github.com/supergrub/supergrub/tree/loopbackcfg-doc in a github (or another public git website) forked repo

**Comment by CollaboratorGCM** [comment]
NOt sure if this is proof, but certainly [**Puppy Linux developers have taken a successful step**](https://github.com/puppylinux-woof-CE/woof-CE/issues/1672#issuecomment-557912177) to take advantage of the work you've outlined. Great!

**Comment by adrian15** [comment]
> NOt sure if this is proof, but certainly [**Puppy Linux developers have taken a successful step**](https://github.com/puppylinux-woof-CE/woof-CE/issues/1672#issuecomment-557912177) to take advantage of the work you've outlined. Great!

Not, this is not a proof. Apparently anything that it's inside Github is the same thing for you. Guess what a branch from a repo is not the same thing as a branch from another repo.

Here there are some newbie-friendly instructions:

1. Visit: https://github.com/supergrub/supergrub and click on top right Fork button
2. Accept to fork the project. (Wait till is completely forked.)
3. Visit: https://github.com/CollaboratorGCM/supergrub/blob/loopbackcfg-doc/README.loopback.cfg.md and press the pen icon (Edit this file).
4. Start contributing on the README.loopback.cfg.md file contents as I asked long time ago.
5. When your edit has been completed write down a summary of work in a line in Commit changes section below.
6. Keep selected _Commit directly to the loopbackcfg-doc branch_ option.
7. Click on **Commit changes** button.

Repeat from 3rd to 7th steps as many times as you need.

Once you have done this you can ping me here to check on your work.

No need to:
 - Bother other people on contributing here
 - Install complex tools on your computer

 As you can see everything can be done from the web.

**Comment by CollaboratorGCM** [comment]
I understand your suggestion. I am not a distro developer but have appealed to the PUPPY Linux WOOFCE GIT on this.

I do have one final question: Is there a sample of some other "fork" I can review to see how someone else has approached their fork? If so, please post a link here OR send to my email.

Thanks in advance

**Comment by adrian15** [comment]
> I understand your suggestion. I am not the distro developer but have appealed to the PUPPY Linux WOOFCE GIT on this. The Puppy Linux development community is rushing toward several releases over the next 60 days.

I don't think you need to appeal on them at all.

> I do have one final question: Is there a sample of some other "fork" I can review to see how someone else has approached their fork? If so, please post a link here OR send to my email.

I don't think there was an specific documentation fork. The most similar is this pull request: https://github.com/supergrub/supergrub/pull/32 .

> Thanks in advance

Just to be clear here I don't want you to write all this new documentation from scratch. The idea is you recollecting what I explain here into the appropiated sections on the document draft.

My former explanation on _How an installed distro boots_ was not for trying to help you on understanding the whole process but what should be filled as a commit into the https://github.com/supergrub/supergrub/blob/loopbackcfg-doc/README.loopback.cfg.md document.

One approach if that you copy-and-paste the whole text as-is and then add one or commits fixing the text. You can fix typos. You can rewrite some sentences so that it's more understandable or rewrite whole paragraphs.

You can, of course, ask about me about any doubt you have.

Once you manage to handle with this first mini-task I'll resume on my explanations (as new comments on this same issue we are talking right now) which I don't mind writing here from time to time (three or four times per week) so that you can continue to shape the documentation thanks to new commits.

The reason why you are the best person to write this documentation is that you are not an expert and thus you will be able to rewrite my high-level explanation into low-level explanations. So that's a documentation for everyone.

Finally I want to emphasize that you don't have to be careful about commits at all. Make as many as you need and don't worry if their descriptions are accurate or not. Once the work is completed all of these commits will be mixed into a single commit on my side thanks to a git operation named squash.

So feel free to make mistakes and learn from them.

Hopefully you can reconsider my offer in a positive way.

**Comment by CollaboratorGCM** [comment]
> Hopefully you can reconsider my offer in a positive way.
I am positive and have always perceived your objective. But, as one who has only used GIT sparingly in my past century. Its a learning curb, as well, in various creates, forks, puts and pulls.

I will over the next week take a stab, personally, or with help, to start the fork as you ask.

I do understand the value you are guiding toward.

**Comment by CollaboratorGCM** [comment]
The Puppy community has responded with some minor changes to allow boots via SG2D's IMG running on a USB.

My steps:
1. Created the USB as you prescribed
2. On a secondary partition, I created a folder for ISOs; namely /BOOTISOS
3. Added Rescatux, Caine, 3 Puppy distros to /BOOTISOS
4. Booted the USB
5. Selected the initial SG2D menu item
6. The menu item supplied a list of bootable ISOs of those distros in the /BOOTISOS folder
7. Every ISO in that folder was tested and each successfully booted to its desktop(s).

It was reported on GIT to the **[Puppy community, here](https://github.com/puppylinux-woof-CE/woof-CE/issues/1618#issuecomment-567241236)**.

**Comment by CollaboratorGCM** [comment]
I have created a step by step document to boot the new Puppy Linux ISO files that are being produced.

It can be found [**publicly here**](https://)

**Comment by adrian15** [comment]
> I have created a step by step document to boot the new Puppy Linux ISO files that are being produced.
> 
> It can be found [**publicly here**](https://docs.google.com/document/d/1bZF7td75blCjA4tjFHjbHxfUEYywEQaUw0yZ6W8q_Vg/edit#)

> priviledges

Check spelling.

> Disadvantages
>  None

Maybe not being able to do persistence? Or can you?

> mkdir -p  /mnt/sdb1/BOOTISOS

You are supposed to use the BOOTISOS folder found on the second partition of the SG2D USB image. Not creating a folder into the SG2D first partition.

If you create the BOOTISOS folder manually where you say then the ISOs won't be found unless some SG2D options are tweaked manually.

Have you ever tried your own howto from the scratch with an empty usb pendrive?

**Comment by CollaboratorGCM** [comment]
Well yes. But those directions were created from memory as well as a more
recent test where I used your beta2 ISO burned onto a CDRW placing a ISOs
folder on the system's NTFS HDD as "/boot-isos".

I booted the CDRW on an UEFI PC. From the SG2D Menu I selected the 1st
option. SG2D found ALL of those ISOs that are shown and booted each when
they were selected.

I find SG2D "EXCELLENT" for creating a folder on a non-booted storage
device containing appropriate ISOs in an appropriate folder, and
SG2D presenting those for user selection to boot.

I am aware that SG2D does so much more, but for this simple step, *it is
excellent!!!* I merely, now, find appropriate ISO(s), drop them into the
boot-isos folder restart the machine to select the CDRW as the boot device
with the SG2D disc and everything works to boot to desktop.

You are an editor of that document. I will repeat those document steps
using a USB which is setup using your recommended IMG beta2 and confirm
that the steps work the same as it is working from the CDRW. If I find it
is in error, I will correct the steps to match both booting SG2D from
CDRW as well as booting SG2D from USB.

Your SG2D effort has so many more implecations in the kinds of people who
could/would find this boot tool useful; namely

   - tire-kicking users who would boot several ISOs,
   - developers who would want to test their work vs priors they have,
   - Virtual Machine users who keep their ISOs in one folder,
   - those who have one ISO for normal internet use and a 2nd for Banking
   or private use,
   - etc.

In ANY event, I want to thank you for all you have done to advance your
work to the open source community for evaluation and use. And, I want to
personally Thank YOU for your efforts to give me good information to manage
to get this far.

Happy Holidays to you, your family, and your community.

PEACE BE WTIH YOU!

**Comment by CollaboratorGCM** [comment]
P.S. On your question of persistence, YES! I have tested that using FATDOG.
In the FATDOG's Menu I select the options for persistence and when I reboot
it, the persistence file on the HDD is found and at desktop, all of the
session changes persist.

**Comment by CollaboratorGCM** [comment]
Here's my most recent test:

1. I downloaded this 16MB ISO () and burned it to a CDRW.
2. On the system's HDD I created the folder "/mnt/sda2/boot-isos" and copy a few ISOs to it.
3. I rebooted the PC: At the SG2D Menu I hit the enter key (1st option)
4. In less than a minute, bootable were being displayed
5. Upon completion of the search I had a list of the install OS on the HDD as well as the ISO in the boot-isos folder
6. I selected one of the ISOs and it booted.
7. I rearranged various items within the booted system and upon shutdown, I allowed it to create a save (persistence) to the HDD.
8. Upon reboot, I followed the sames steps to get to the SG2D bootables selection screen and selected the very same ISO.
9. Upon its reboot, it found its persistence and open to a desktop with ALL of the elements before its original shutdown

This matches the items in the document.

ALL IS WELL!

Is this what you wanted verified?

**Comment by adrian15** [comment]
> ALL IS WELL!
>
> Is this what you wanted verified

Not at all.

Your documentation should be rewritten on using: supergrub2-2.04s2-beta2-multiarch-USB.img.zip on a USB device. For the BOOTISOS part it should be using the second partition on that same usb device where you transfer supergrub2-2.04s2-beta2-multiarch-USB.img to.

**Comment by CollaboratorGCM** [comment]
Corrected.

**Comment by adrian15** [comment]
> Corrected.

Now it's ok. Even if James Bond is there in the screenshot XD .

You can also use the Boot manually. Boot ISOs steps to speed up things if you want to.

How would you recommend about renaming a file so that "Boot ISOs" was automatically run ?
What are your expectations as a final user?

**Comment by CollaboratorGCM** [comment]
Expectation...? Merely to help!

I felt the need to clarify the ease of use you have with this feature of SG2D. I think it is a much needed utility and a few/lot will take advantage of it.  For example, the Puppy Linux community produces many-many distributions during the course of the year. If member there alone, understood the presentation you have provided AND the distro developers will continue forward in their production of "compatible" (loopback.cfg) creations, SG2D will be useful. With it users could house their ISOs centrally and merely select which to boot for productive or test purposes as well as boot their Windows should they need.

SG2D looks extremely useful IMHO.

Thanks Adrian for your guidance.

**Comment by adrian15** [comment]
> Expectation...? Merely to help!

Let me reask the question then. What do you suggest as you being a final user?
If you could just rename a file so that the default SG2D behaviour changed into:

* Show menu where you can use the default SG2D main menu
* Wait 30 seconds and then run "Boot ISOs" option.

Would you change the timeout?
What file would you rename?

Any other related idea?

**Comment by adrian15** [comment]
> I will write a 2nd document describing use of the ISO mentioned 2 PUP above. Thus we will cover use of a USB to boot SG2D and use of a CD/DVD to boot SG2D.

Yeah, that might be useful for some users.

My default advice is using the USB one so that you can carry those isos in the pendrive. That way you don't depend on an internal hard disk partition which might fail one day or another. That's why I insisted.

But, yeah, any other additional documentation is appreciated.

> Hopefully some users will find it easy to follow a process to have a folder of multiple ISOs which can be presented by SG2D for booting.

Probably.

> I ask: Would you contribute a disclaimer to the current document regarding the requirement for GRUB2 and a loopback.cfg. IN YOUR OWN WORDS. If need I can help to insure it get the meaning across that you want users to be aware of for booting ISOs in the BOOTISOS folder, please?
> 
> Thanks in advance.

Well, that's what I wanted to explain here in detail if you wanted to make a fork and a pull request. So that it can be on an official txt file and you can just link to it and get the full explanation.

But a short summary would be: Isos supported by SG2D have a /boot/grub/loopback.cfg or /grub/loopback.cfg in them where the `$iso_path` variable is passed with the relative path to the iso. It's up to the kernel, initrd and other scripts to use the specific iso file.

**Comment by adrian15** [comment]
> I felt the need to clarify the ease of use you have with this feature of SG2D. I think it is a much needed utility and a few/lot will take advantage of it. For example, the Puppy Linux community produces many-many distributions during the course of the year. If member there alone, understood the presentation you have provided AND the distro developers will continue forward in their production of "compatible" (loopback.cfg) creations, SG2D will be useful. With it users could house their ISOs centrally and merely select which to boot for productive or test purposes as well as boot their Windows should they need.

I'm not sure it will be so disruptive as you think :). Please note that virtualization exists where Puppy developers can try their produced isos. The only benefit is if you want to try something virtualization cannot emulate.

**Comment by CollaboratorGCM** [comment]
You made a comment referencing @Jamesbond, earlier. Were you referring to his several helpful comments **[on booting here?](https://github.com/puppylinux-woof-CE/woof-CE/issues/1618#issuecomment-562425932)**

On virtualization, yes and I have a proponent user for over 3 decades. But in the Puppy Linux community I am willing to bet that of the thousands of users since 2005 when I joined, there are ONLY a half-dozen, maybe, who actually use virtualization on any regular basis. I found and reported over 5 years ago that couple of their distros were "faster" in desktop services using KVM on hardware capable processors than the actual hosts. But, most users have little understanding of this ability to emulate X86 and ARM technologies ... even as I have worked with others generating a manual to ease understanding and providing directions on use.

In any event, SG2D can be just as useful in a KVM-QEMU virtual environment just as it is in a "real" boot environment. Thus there is a UNIVERSALITY that it provides when considering VMs as well as Live boots.

The author of Puppy Linux, himself, does not appear to use a KVM opting to create his personal version of Docker which seemingly works very well even though he has to constantly service it versus using a docker where he would not have to develop it. But, I applaud what that author has done as he continues to improve his version of container usage.

If I were to point you to a PUP distro that you could test with little to no investment except to review, I would suggest the upcoming FATDOG and BIONICPUP due in just a couple of days. FATDOG is a T2+Slackware generated derivative while BIONICPUP is a GIT WOOFCE generated distro for Puppy Linux. Expect both of these to show up on distrowatch as production quality replacements between now and 1st week of January.

Do not expect that the Puppy author, Barry Kauler, to make an ISO version of his work. He departed couple years ago and uses his own, personal available, generator for his distros. Further he is not in favor of ISOs anymore, rather concentrating of generating IMG (images) as the way forward for him.

I think that in the future GRUB developers will begin to publish "direct capable image (IMG) booting" just as you have produced and published on "direct booting ISOs" with what you do with SG2D.

That ability to boot from file may be the next frontier in a helper facility like what you do in SG2D.

**Comment by adrian15** [comment]
> You made a comment referencing @JamesBond, earlier. Were you referring to his several helpful comments **[on booting here?](https://github.com/puppylinux-woof-CE/woof-CE/issues/1618#issuecomment-562425932)**

No. In your document there is an screenshot where a folder named 2JamesBond is found next to the BOOTISOS folder. It might be easier to relate for readers of that document is the screenshot did not have such a folder which I guess it's something you add manually to the SG2D USB second partition.

**Comment by CollaboratorGCM** [comment]
**Document changed to reduce potential confusion.**

**Comment by CollaboratorGCM** [comment]
Skip ALL of my comments about booting IMGs. Its an unreasonable statement given what they are designed to do to storage media vs desktop operations. There are all kinds of dangers inherent in booting IMGs files directly!!!

**Comment by adrian15** [comment]
Ah, you meant loop-mounting into img files and then booting a kernel inside of it?

Yeah, it does not make too much sense.
In that case an standard would be needed to know what's the boot partition (1st one, 2nd one) and what to load exactly.

**Comment by adrian15** [comment]
PENDING: Documentation fork from @CollaboratorGCM for improving loopback.cfg documentation.

**Comment by adrian15** [comment]
This has been open for a long time without any more feedback.
I close the issue.

**Comment by johnwmail** [comment]
Hi all,
So, any links about "how to boot an ISO within /boot/boot-isos"? 
I still cannot make it works.

**Comment by CollaboratorGCM** [comment]
Saw this open for few weeks. 

This post does NOT directly answer your question, but does show a working example. Using the steps **[HERE](https://forum.puppylinux.com/viewtopic.php?p=1894#p1894)**, it is finding ISOs.
