### ISSUE TITLE
SuperGRUB2 chainload

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#70]
Adrian, could you help in **[some understanding of this](https://github.com/puppylinux-woof-CE/woof-CE/issues/1672#issuecomment-583928603)**?

What insight is attempted?

**Comment by CollaboratorGCM** [comment]
Several requests in this post

1. there a guide to steps to use GRUB2 to create the loopback.cfg that is needed for SG2D to boot an ISO?
2. If one drops out of a SG2D boot to the GRUB2 command-line, and a set/string of commands would lead to a OS's boot, is there a way to save the GRUB2 commands?
3. Is there a set of command-line steps that would mimic what a loopback.cfg does to direct booting and ISO? (on one of my ISO, its loopback.cfg contains a single line "source /grub.cfg". How would I use something similar for an ISO without a loopback.cfg but has a grub.cfg?)

Thanks in advance for any guidance you can share.

**Comment by adrian15** [comment]
> there a guide to steps to use GRUB2 to create the loopback.cfg that is needed for SG2D to boot an ISO?

No. It depends on each distribution. You can check other distros's loopback.cfg in order to do it.
Anyways having a loopback.cfg is not useful unless the distro live cd initrd image is modified to support loop booting from an iso (from a kernel standpoint).



> If one drops out of a SG2D boot to the GRUB2 command-line, and a set/string of commands would lead to a OS's boot, is there a way to save the GRUB2 commands?

No. But you can have a sgd_custom.cfg file where either main.cfg resides or at boot/grub directory and those entries will be added to the botton of SG2D menu.

> Is there a set of command-line steps that would mimic what a loopback.cfg does to direct booting and ISO? (on one of my ISO, its loopback.cfg contains a single line "source /grub.cfg". How would I use something similar for an ISO without a loopback.cfg but has a grub.cfg?)

No sense. Check my first reply again.
