### ISSUE TITLE
1

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#79]
@adrian15 please consider help/advice **[on this](https://forum.puppylinux.com/viewtopic.php?p=8970#p8970)**

**Comment by adrian15** [comment]
Forum cannot be reached. Please open a new bug when you it's available.

Or better even... NEVER EVER AGAIN open a bug telling us to read another external url.

You copy and paste whatever your question or doubt is here and then you link to the specific thread so that we can check it for additional information.
